import { useEffect, useState } from 'react'
import './App.css'
import './detail.css'
import './doctor.css'
import './pageviews.css'

const services = [['✚', 'General Medicine', 'Everyday consultations, preventive health checks and long-term care plans.'], ['♧', 'Mother & Child Care', 'Gentle support for pregnancy, newborn care and growing families.'], ['◌', 'Mental Wellness', 'Private, compassionate counselling for a healthier mind and life.'], ['⌁', 'Diagnostics', 'Reliable tests and reports with clear guidance from our medical team.']]
const doctors = [{ name: 'Dr. Aditi Rawat', role: 'General Physician', image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=700&q=85', experience: '14 years of experience', focus: 'Preventive health, chronic care and family medicine', languages: 'Hindi, English, Garhwali', time: 'Mon–Sat · 9 AM–2 PM' }, { name: 'Dr. Rohan Mehta', role: 'Child & Family Care', image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=700&q=85', experience: '11 years of experience', focus: 'Child wellness, newborn care and family health', languages: 'Hindi, English', time: 'Mon–Sun · 11 AM–6 PM' }, { name: 'Dr. Naina Kapoor', role: 'Wellness Consultant', image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=700&q=85', experience: '9 years of experience', focus: 'Mental wellness, stress support and lifestyle care', languages: 'Hindi, English', time: 'Tue–Sun · 10 AM–5 PM' }]
function Logo() { return <a className="logo" href="/"><span>+</span><i>GANGA</i> AROGYA NIKUNJ</a> }

const pageCopy = {
  about: ['About Ganga Arogya Nikunj', 'Rooted in Rishikesh, our clinic brings together experienced care, a peaceful setting and a deep respect for every patient.', 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1600&q=85'],
  services: ['Healthcare services', 'Explore thoughtful everyday care, family support, wellness consultations and diagnostics in Rishikesh.', 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1600&q=85'],
  doctors: ['Meet our care team', 'Our doctors take time to listen, explain and create practical next steps for your health.', 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1600&q=85'],
  contact: ['Visit our Rishikesh clinic', 'Near the Ganga and Triveni Ghat, find a calm space for dependable everyday healthcare.', 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1600&q=85'],
}
function DetailPage({ slug, onBook, booking, closeBooking }) {
  const service = services.find(s => slug === `service-${s[1].toLowerCase().replaceAll(' ', '-')}`)
  const [title, description, image] = service ? [service[1], service[2], 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1600&q=85'] : pageCopy[slug]
  const whatsapp = `https://wa.me/919999999999?text=${encodeURIComponent(`Namaste, I would like to book a slot for ${title} at Ganga Arogya Nikunj, Rishikesh.`)}`
  return <><div className="topline"><span>Care among the hills of Rishikesh</span><a href="tel:+919999999999">Call us: <b>+91 99999 99999</b></a></div><header><Logo /><nav className="page-nav"><a href="#home">Home</a><a href="#about">About</a><a href="#services">Services</a><a href="#doctors">Doctors</a><a href="#contact">Contact</a></nav><button className="book-button desktop-book" onClick={() => onBook(service?.[1])}>Book appointment →</button></header><section className="detail-hero" style={{ backgroundImage: `linear-gradient(90deg,#103d35e8,#164f4782),url(${image})` }}><div><p className="eyebrow light">GANGA AROGYA NIKUNJ · RISHIKESH</p><h1>{title}</h1><p>{description}</p></div></section><section className="detail-content"><article><p className="eyebrow">PERSONALISED CARE</p><h2>Your wellbeing, held with <em>attention.</em></h2><p>Our team will understand your needs, guide you clearly and make your visit as comfortable as possible. Book online, or speak directly to our team on WhatsApp for help selecting a time.</p><div className="detail-points"><span>✓ Compassionate clinical guidance</span><span>✓ Convenient slot confirmations</span><span>✓ Peaceful Rishikesh care environment</span></div></article><aside><p className="eyebrow">BOOK A SLOT</p><h3>Ready when you are.</h3><button className="book-button" onClick={() => onBook(service?.[1])}>Book on website →</button><a className="whatsapp-button" href={whatsapp} target="_blank" rel="noreferrer">Book on WhatsApp ↗</a><small>We will confirm your appointment shortly.</small></aside></section><section className="green-strip"><p>Fresh air. Thoughtful medicine. A kinder path to feeling better.</p><a href="#contact">Find our clinic →</a></section><footer><div className="footer-bottom"><span>© 2026 Ganga Arogya Nikunj. All rights reserved.</span><span>Rishikesh, Uttarakhand</span></div></footer>{booking && <div className="modal-backdrop" onClick={closeBooking}><section className="booking-modal" onClick={e => e.stopPropagation()}><button className="close" onClick={closeBooking}>×</button><p className="eyebrow">APPOINTMENT REQUEST</p><h2>Let’s plan your visit.</h2><p>For {title}, our Rishikesh care team will confirm your preferred time.</p><form onSubmit={e => { e.preventDefault(); closeBooking() }}><input required placeholder="Your full name" /><input required type="tel" placeholder="Mobile number" /><button className="book-button" type="submit">Request appointment →</button></form></section></div>}</>
}

function SitePage({ page }) {
  const content = { about: ['About our clinic', 'A peaceful Rishikesh clinic where capable medicine meets kindness.', 'Our approach', ['Listen first', 'Explain clearly', 'Care continuously']], services: ['Our healthcare services', 'Support for everyday health, family milestones and a calmer mind.', 'Choose your care', services.map(s => s[1])], doctors: ['Meet our doctors', 'Experienced people who make care feel clearer and more personal.', 'Our care team', doctors.map(d => d.name)], contact: ['Visit us in Rishikesh', 'Come find us near Triveni Ghat, surrounded by the calm of the Ganga valley.', 'Clinic information', ['Near Triveni Ghat, Rishikesh', '+91 99999 99999', 'Daily: 8 AM – 8 PM']] }[page]
  const image = page === 'contact' ? 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=85' : page === 'doctors' ? 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1400&q=85' : 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1400&q=85'
  return <main className={`site-page ${page}-page`}><div className="topline"><span>Ganga Arogya Nikunj · Rishikesh</span><a href="#home">Back to home</a></div><header><Logo /><nav className="page-nav"><a href="#home">Home</a><a href="#about">About</a><a href="#services">Services</a><a href="#doctors">Doctors</a><a href="#contact">Contact</a></nav></header><section className="page-banner"><div><p className="eyebrow light">GANGA AROGYA NIKUNJ</p><h1>{content[0]}</h1><p>{content[1]}</p></div><img src={image} alt="Rishikesh healthcare" /></section><section className="page-body"><div><p className="eyebrow">{content[2].toUpperCase()}</p><h2>Designed around your <em>wellbeing.</em></h2><p className="page-lead">Every visit is rooted in attentive guidance, a calm environment and practical next steps for you and your family.</p></div><div className="page-list">{content[3].map((item, index) => <article key={item}><b>0{index + 1}</b><h3>{item}</h3><p>{page === 'services' ? 'Explore details, consultation support and easy appointment booking.' : 'Thoughtful care, in a setting shaped by the greenery of Rishikesh.'}</p>{page === 'services' && <a href={`#service-${item.toLowerCase().replaceAll(' ', '-')}`}>View service →</a>}</article>)}</div></section>{page === 'contact' && <iframe className="page-map" title="Rishikesh clinic map" src="https://www.google.com/maps?q=Triveni%20Ghat%2C%20Rishikesh&z=14&output=embed" loading="lazy" />}{page === 'doctors' && <section className="doctor-page-cards">{doctors.map(d => <article key={d.name}><img src={d.image} alt={d.name} /><h3>{d.name}</h3><p>{d.role}</p></article>)}</section>}<section className="green-strip"><p>Fresh air, clearer guidance and care that stays close.</p><a href="#home">Return home →</a></section></main>
}

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false); const [booking, setBooking] = useState(false); const [notice, setNotice] = useState(''); const [selectedService, setSelectedService] = useState(''); const [selectedDoctor, setSelectedDoctor] = useState(null)
  const currentPage = () => { const path = window.location.pathname.replace(/^\//, ''); return path || window.location.hash.slice(1) || 'home' }
  const [page, setPage] = useState(currentPage)
  useEffect(() => { const change = () => { const hash = window.location.hash.slice(1); if (window.location.pathname !== '/' && hash) { window.location.assign(hash === 'home' ? '/' : `/${hash}`); return } setPage(currentPage()) }; window.addEventListener('hashchange', change); window.addEventListener('popstate', change); return () => { window.removeEventListener('hashchange', change); window.removeEventListener('popstate', change) } }, [])
  const flash = text => { setNotice(text); window.setTimeout(() => setNotice(''), 3000) }
  const nav = [['Home', '/'], ['About', '/about'], ['Services', '/services'], ['Doctors', '/doctors'], ['Contact', '/contact']]
  const openBooking = service => { setSelectedService(service || ''); setBooking(true) }
  if (['about', 'services', 'doctors', 'contact'].includes(page)) return <SitePage page={page} />
  if (page !== 'home') return <DetailPage slug={page} onBook={openBooking} booking={booking} closeBooking={() => setBooking(false)} />
  return <main id="home">
    {notice && <div className="notice">{notice}</div>}
    <div className="topline"><span>24/7 emergency guidance · Rishikesh, Uttarakhand</span><a href="tel:+919999999999">Call us: <b>+91 99999 99999</b></a></div>
    <header><Logo /><button className="menu-button" aria-label="Toggle menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? '×' : '☰'}</button><nav className={menuOpen ? 'open' : ''}>{nav.map(([label, link]) => <a key={label} href={link} onClick={() => setMenuOpen(false)}>{label}</a>)}<button className="mobile-book" onClick={() => { setMenuOpen(false); openBooking() }}>Book appointment</button></nav><button className="book-button desktop-book" onClick={() => openBooking()}>Book appointment <span>→</span></button></header>
    <section className="hero-section"><video className="hero-video" autoPlay muted loop playsInline poster="https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1800&q=85"><source src="https://videos.pexels.com/video-files/4021932/4021932-hd_1920_1080_25fps.mp4" type="video/mp4" /></video><div className="hero-shade" /><div className="hero-copy"><p className="eyebrow light">WELCOME TO GANGA AROGYA NIKUNJ</p><h1>Care that feels<br /><em>close to home.</em></h1><p>Thoughtful, dependable healthcare for every generation—surrounded by the calm of Rishikesh.</p><div className="hero-actions"><button className="book-button" onClick={() => setBooking(true)}>Book a visit <span>→</span></button><a className="watch-link" href="#about">Discover our care <b>↓</b></a></div><div className="hero-trust"><b>15+ years</b><span>of trusted care in the community</span></div></div></section>
    <section className="quick-care"><div><b>24/7</b><span>Emergency guidance</span></div><div><b>8 AM–8 PM</b><span>Daily OPD hours</span></div><div><b>Same day</b><span>Appointment slots</span></div><a href="#contact">Get directions →</a></section>
    <section className="about-section" id="about"><div className="about-image"><img src="https://images.unsplash.com/photo-1584982751601-97dcc096659c?auto=format&fit=crop&w=1200&q=85" alt="Doctor speaking with a patient" /><div className="image-badge"><strong>48k+</strong><span>people supported</span></div></div><div className="about-copy"><p className="eyebrow">CARE, WITH INTENTION</p><h2>Medicine with a <em>human touch.</em></h2><p>We combine experienced medical care with the time, clarity and kindness every patient deserves. From everyday concerns to family wellness, our team is here to help you feel heard.</p><div className="check-list"><span>✓ Trusted doctors and clear advice</span><span>✓ Calm, clean and welcoming spaces</span><span>✓ Care plans built around your life</span></div><a className="text-link" href="#doctors">Meet our care team →</a></div></section>
    <section className="services-section" id="services"><div className="section-intro"><div><p className="eyebrow">OUR SERVICES</p><h2>Care for every chapter<br />of your <em>life.</em></h2></div><p>Whether you need a regular check-up or a more personal conversation, start here.</p></div><div className="service-grid">{services.map(([icon, title, text], i) => <article className={'service service-' + i} key={title}><div className="service-icon">{icon}</div><h3>{title}</h3><p>{text}</p><a className="service-detail" href={`#service-${title.toLowerCase().replaceAll(' ', '-')}`}>View details & book <span>→</span></a></article>)}</div></section>
    <section className="journey"><div><p className="eyebrow light">YOUR VISIT, MADE SIMPLE</p><h2>Feel prepared from<br />the <em>first hello.</em></h2></div><div className="journey-steps"><article><b>01</b><h3>Choose a service</h3><p>Find the right support for you or your family.</p></article><article><b>02</b><h3>Book your time</h3><p>Pick a convenient slot online or by phone.</p></article><article><b>03</b><h3>Meet your doctor</h3><p>Receive attentive care and a clear next step.</p></article></div></section>
    <section className="doctors-section" id="doctors"><div className="section-intro"><div><p className="eyebrow">OUR CARE TEAM</p><h2>Good care starts with<br />good <em>people.</em></h2></div><button className="outline-button" onClick={() => setBooking(true)}>Find a doctor →</button></div><div className="doctor-grid">{doctors.map(doctor => <article className="doctor" key={doctor.name} tabIndex="0" role="button" onClick={() => setSelectedDoctor(doctor)} onKeyDown={e => e.key === 'Enter' && setSelectedDoctor(doctor)}><img src={doctor.image} alt={doctor.name} /><div><h3>{doctor.name}</h3><p>{doctor.role}</p><span>View profile →</span></div></article>)}</div></section>
    <section className="appointment-banner"><div><p className="eyebrow light">HERE WHEN YOU NEED US</p><h2>Take the first step<br />towards feeling <em>better.</em></h2><p>Our team will help you find the right care and a time that works for you.</p></div><button className="light-button" onClick={() => setBooking(true)}>Book an appointment →</button></section>
    <section className="location-section" id="contact"><div className="location-copy"><p className="eyebrow">VISIT OUR CLINIC</p><h2>Find calm, capable<br />care in <em>Rishikesh.</em></h2><p>Near Triveni Ghat, Rishikesh, Uttarakhand 249201</p><a href="tel:+919999999999">+91 99999 99999</a><a href="mailto:care@gangaarogya.in">care@gangaarogya.in</a><p className="hours"><b>Clinic hours</b><br />Monday – Sunday · 8:00 AM – 8:00 PM</p></div><iframe title="Clinic location map" className="map" src="https://www.google.com/maps?q=Triveni%20Ghat%2C%20Rishikesh&z=14&output=embed" loading="lazy" /></section>
    <footer><div className="footer-main"><div><Logo /><p>Healthcare with heart, for Rishikesh and every family we serve.</p></div><div><h4>Explore</h4><a href="#about">About us</a><a href="#services">Our services</a><a href="#doctors">Our doctors</a></div><div><h4>Patient care</h4><button onClick={() => setBooking(true)}>Book appointment</button><a href="#contact">Location & hours</a><a href="tel:+919999999999">Emergency help</a></div><div><h4>Stay connected</h4><a href="#home">Instagram</a><a href="#home">Facebook</a><a href="mailto:care@gangaarogya.in">Email us</a></div></div><div className="footer-bottom"><span>© 2026 Ganga Arogya Nikunj. All rights reserved.</span><span>Privacy · Terms of care</span></div></footer>
    {booking && <div className="modal-backdrop" onClick={() => setBooking(false)}><section className="booking-modal" onClick={e => e.stopPropagation()}><button className="close" onClick={() => setBooking(false)}>×</button><p className="eyebrow">APPOINTMENT REQUEST</p><h2>Let’s plan your visit.</h2><p>Tell us a little about yourself and our care team will call to confirm your slot.</p><form onSubmit={e => { e.preventDefault(); setBooking(false); flash('Thank you—your appointment request is received.') }}><input required placeholder="Your full name" /><input required type="tel" placeholder="Mobile number" /><select value={selectedService} onChange={e => setSelectedService(e.target.value)} required><option value="" disabled>Choose a service</option>{services.map(s => <option key={s[1]}>{s[1]}</option>)}</select><button className="book-button" type="submit">Request appointment →</button></form></section></div>}
    {selectedDoctor && <div className="modal-backdrop" onClick={() => setSelectedDoctor(null)}><section className="doctor-modal" onClick={e => e.stopPropagation()}><button className="close" onClick={() => setSelectedDoctor(null)}>×</button><img src={selectedDoctor.image} alt={selectedDoctor.name} /><div className="doctor-modal-copy"><p className="eyebrow">MEET YOUR DOCTOR</p><h2>{selectedDoctor.name}</h2><h4>{selectedDoctor.role}</h4><p>{selectedDoctor.focus}. {selectedDoctor.experience} serving individuals and families in Rishikesh.</p><div className="doctor-facts"><span><b>Experience</b>{selectedDoctor.experience}</span><span><b>Languages</b>{selectedDoctor.languages}</span><span><b>Consultation hours</b>{selectedDoctor.time}</span></div><button className="book-button" onClick={() => { setSelectedDoctor(null); openBooking(selectedDoctor.role) }}>Book with {selectedDoctor.name.split(' ')[1]} →</button></div></section></div>}
  </main>
}
